name: Build and test

on:
  push:
    branches:
      - '!main'
  pull_request:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name : Checkout Repo
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100

    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Run dotnet format
      run: dotnet format lit-redis.sln --verify-no-changes

    - name: Install dependencies
      run: dotnet restore lit-redis.sln

    - name: Build
      run: dotnet build lit-redis.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test lit-redis.sln --logger GitHubActions --no-restore --verbosity normal
