name: Build, Test, and Release

on:
  push:
    branches:
      - main

jobs:
  build_test_and_release:
    name: Build, test, and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100

    - name: Install dependencies
      run: dotnet restore lit-redis.sln

    - name: Build
      run: dotnet build lit-redis.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test lit-redis.sln --logger GitHubActions --no-restore --verbosity normal

    - name: Publish Core
      uses: rohith/publish-nuget@v2
      with:
         PROJECT_FILE_PATH: LitRedis.Core/LitRedis.Core.csproj
         NUGET_KEY: ${{secrets.FIREBEND_NUGET_KEY}}
         TAG_COMMIT: false
